### ISSUE TITLE
Propogate legend_values and legend_labels to colorbar legend

### ISSUE THREAD

**Issue by ResidentMario** [ResidentMario/geoplot#144]
There are currently two types of legends in `geoplot`. If your legend variable is `hue` and you use a continuous colormap (`k=None`), a [colorbar legend](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.colorbar.html) will be used. If your legend variable is `hue` and you use a categorical colormap (`k!=None`), or otherwise your legend variable is `scale`, a [regular legend](https://matplotlib.org/users/legend_guide.html) will be used.

The `legend_values` and `legend_labels` keyword arguments can be used to toggle the values and labels in a regular legend only. However, it makes sense for these parameter to also be usable for setting [tick values and labels](https://matplotlib.org/gallery/ticks_and_spines/colorbar_tick_labelling_demo.html) on a colorbar legend as well. Currently attempting to do so will raise a `NotImplementedError`; we can do better than that.

**Comment by coolum001** [comment]
Hi

first of all, thanks for this package.

Secondly, even if you have discrete (set of values) colormap, you still get a colorbar.

The example below (working code) is one where I have a numeric value 'Crash_Years', but only a small number of unique values.  I created a discrete colormap by the code

```
    cmap=plt.cm.get_cmap(
        'inferno',
        fatal_gdf['Crash_Year'].max()
        - fatal_gdf['Crash_Year'].min(),
    ),
```

but I get a colorbar.  As you can see, I can feed parameters to the colorbar through the ```legend_kwargs``` parameter (in this case ```{'orientation': 'vertical'},```), so this makes the parameter name ```legend_kwargs``` a little misleading. It really is  "legend or colorbar keyword parameters, depending upon the context".

```
fig = plt.figure(figsize=(20, 20))
ax = fig.add_subplot(1, 1, 1, projection=gcrs.WebMercator())

gplt.webmap(
    fatal_gdf,
    ax=ax,
    projection=gcrs.WebMercator(),
    extent=(153, -26.6, 153.2, -26.4),
)
gplt.pointplot(
    fatal_gdf,
    ax=ax,
    alpha=0.9,
    extent=(153, -26.6, 153.2, -26.4),
    hue='Crash_Year',
    cmap=plt.cm.get_cmap(
        'inferno',
        fatal_gdf['Crash_Year'].max()
        - fatal_gdf['Crash_Year'].min(),
    ),
    legend=True,
    legend_kwargs={'orientation': 'vertical'},
    s=20,
)
```


You may be interest in my re-formatting of the geopandas colorbar.

```
def format_colorbar(
    figure, map_title: str = '', colorbar_title: str = ''
) -> None:
    '''
    format_color: format figure with colorbar axes to look nicer
    
    Parameters:
    figure: mapplotlib figure
    map_title: title of map area, defaults to empty
    colorbar_title: title of colorbar, defaults to empty
    
    Returns:
    None
    
    Side Effects:
    The Axes object holding the colorbar is reduced to half height of figure
    Supplied titles are added the map and colorbar Axes objects
    '''
    fig = figure

    # get map and colorbar Axes objects  (latter is call leg_ax for legend Axes,
    # but is not a Legend object)
    map_ax = fig.axes[0]
    leg_ax = fig.axes[1]

    # get bounds of both  Axes objects
    map_box = map_ax.get_position()
    leg_box = leg_ax.get_position()

    # move the bottom of the legend axes to halfway up the figure
    # keep current width
    leg_ax.set_position(
        [
            leg_box.x0,
            map_box.y0 + map_box.height / 2,
            leg_box.width,
            map_box.height / 2,
        ]
    )

    # set title parameters for main map title
    title_font_spec = {
        'fontsize': 30,
        'horizontalalignment': 'right',
    }

    # Use default title (small) for legend
    # use same padding to align title in vertical direction

    leg_ax.set_title(colorbar_title, pad=20)
    map_ax.set_title(
        map_title, fontdict=title_font_spec, pad=20
    )
    return None


# end format_colorbar
```

**Comment by ResidentMario** [comment]
Thanks for reporting. I would quibble with the following statement:

> even if you have discrete (set of values) colormap, you still get a colorbar.

Every colormap passed to `geoplot` is treated as a continuous colormap, even ones that you as the author might consider to be discrete. We cannot usefully infer whether an input `cmap` is continuous or discrete because:

* The code would be very fragile. It would boil down to type inference: is this a `ListedColormap` object? Is this a `LinearSegmentedColormap` object? `ScalarMappable`? Something else?
* The names and constructors that `matplotlib` provides for colormaps are as diverse as they are confusing. `LinearSegmentedColormap` is a continuous colormap and `ListedColormap` is a categorical colormap. Only someone who has been working with `matplotlib` for years would remember that. I constantly forget which is which. Plus, the constructors are totally different.

`geoplot` instead has the following behavior:

* If you input just a `cmap`, and hue is an interval variable (e.g. `int` or `float`), your colormap is treated as continuous, and a colorbar legend is used.
* If you input just a `cmap`, and hue is an object variable (e.g. `str`), the values are treated as categorical, binned discretely, and a categorical legend is used.
* If you input a `cmap` and a `scheme`, a categorical legend is generated using your classification scheme.

Pinning whether or not a legend is categorical to the `scheme` parameter in this way produces simple, reliable, extensible behavior that is easy to understand and easy to extend&mdash;much better than mucking with `matplotlib` colormaps.

> the parameter name legend_kwargs a little misleading. It really is "legend or colorbar keyword parameters, depending upon the context".

I admit that this is a bit of an issue, and something I've always been conscious of, but I think this is an acceptable compromise. This arrangement of API parameters feels better than the alternatives in terms of its tradeoffs.

**Comment by ResidentMario** [comment]
All of that being said, your use case does expose an issue with the current API:

> The example below (working code) is one where I have a numeric value 'Crash_Years', but only a small number of unique values

The design pattern you *should* be able to use is:

```
gplt.pointplot(
    df, hue='Crash_Year', cmap=cmap,
    scheme=<something from mapclassify>, legend=True
)
```

However, it looks like at this time mapclassify doesn't have a discrete categorization scheme. Let me reach out to them to ask, and see what they say.

**Comment by coolum001** [comment]
Thanks very much for your quick response.  I agree that your design choices for the semantics of hue, cmap, and scheme seem the most sensible (especially given the scheme='categorical' option).  I certainly agree with having as little to do as possible with matplotlib colormaps.

I do suggest that the documentation make it clear that the ```legend_kwargs``` keywords could be directed at a ```colorbar``` object, depending upon the context (your three geoplot behaviour bullets points above), because I must admit I was mislead by the parameter name.

I will try your suggested code asap.
Thanks
Don

**Comment by ResidentMario** [comment]
Yeah, I'll add more clearly indicating the intended target for the `legend_kwargs` parameters to my to-do list.

**Comment by coolum001** [comment]
Can confirm that ```scheme="categorical"``` works just fine

Thank you
