### ISSUE TITLE
Set up tests and continuous integration

### ISSUE THREAD

**Issue by ResidentMario** [ResidentMario/geoplot#149]
This library is at (arguably beyond!) the point where real testing infrastructure is needed. File under "chores I've been putting off for a long, long time".

**Comment by QuLogic** [comment]
Yes, tests in 0.3.0 don't seem to pass right now.

**Comment by ResidentMario** [comment]
Ah, yes...I neglected to update the existing test suite in line with the 0.3.0 release.

**Comment by ResidentMario** [comment]
Done in #177.

**Comment by ResidentMario** [comment]
CI done in #180.
