### ISSUE TITLE
no datasets 

### ISSUE THREAD

**Issue by EnvSci** [ResidentMario/geoplot#164]
Hi, I could not manage to load data. Could you please suggest.

import geoplot.crs as gcrs
import geopandas as gpd
cities = gpd.read_file(gplt.datasets.get_path('usa_cities'))
gplt.pointplot(cities)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-95-35bbdafa596b> in <module>
      1 import geoplot.crs as gcrs
      2 import geopandas as gpd
----> 3 cities = gpd.read_file(gplt.datasets.get_path('usa_cities'))
      4 gplt.pointplot(cities)

AttributeError: module 'geoplot' has no attribute 'datasets'

**Comment by ResidentMario** [comment]
The `datasets` submodule was added to `geoplot` in the current release, [0.3.0](https://github.com/ResidentMario/geoplot/releases/tag/0.3.0). If you attempt to import the `datasets` submodule in a prior version of `geoplot`, you will get this error.

To fix this error (and get numerous other improvements to the library), please upgrade to the latest version by running `pip install -U geoplot`.

I am closing this issue now. Let me know if that helps.

**Comment by ishaansharma** [comment]
> The `datasets` submodule was added to `geoplot` in the current release, [0.3.0](https://github.com/ResidentMario/geoplot/releases/tag/0.3.0). If you attempt to import the `datasets` submodule in a prior version of `geoplot`, you will get this error.
> 
> To fix this error (and get numerous other improvements to the library), please upgrade to the latest version by running `pip install -U geoplot`.
> 
> I am closing this issue now. Let me know if that helps.

pip command does not install geoplot in mac . it fails while installing cartopy. 
But once installed with conda , it installed sucessfully. 
but the when I started using geoplot.datasets module it said, 

> AttributeError: module 'geoplot' has no attribute 'datasets' 

How can this be updated using conda. so that we can use datasets of geoplot.
