### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by jGaboardi** [ResidentMario/geoplot#181]
@ResidentMario as more folks are using your awesome package, it may be a good idea for you to create a DOI through [zenodo](https://zenodo.org) for a standard citation format. Most of the packages in the PySAL federation have this (see [`spaghetti`'s example](https://zenodo.org/record/3354578#.XZfOUS2ZPow)).

**Comment by ResidentMario** [comment]
After someone contacted me via email asking for a cite-able, I wrote [a short paper](https://joss.theoj.org/papers/10.21105/joss.00547) for the Journal of Open Source Software that generated an attached DOI. I will probably go this route again for `geoplot`.

**Comment by ResidentMario** [comment]
FWIW, I'm not sure how highly to prioritize this. Mendeley doesn't have any citations listed (yet) for [the `missingno` paper](https://www.mendeley.com/catalogue/missingno-missing-data-visualization-suite/).

**Comment by jGaboardi** [comment]
With `zenodo` you only to make a fresh GitHub release and it only takes a few minutes generate a DOI if you aren't up for writing a paper. 

Just food for thought.

**Comment by jGaboardi** [comment]
I am working, as a (minor) co-author, on a paper with @slumnitz and we would like to cite `geoplot`.

**Comment by ResidentMario** [comment]
Yeah, doing Zenodo alone without the JOSS paper was a much faster process. [All done now](https://zenodo.org/record/3475569).
