### ISSUE TITLE
attribute error when import Geoplot

### ISSUE THREAD

**Issue by gracethedog** [ResidentMario/geoplot#183]
Got the following error when import Geoplot
AttributeError: module 'geoplot' has no attribute 'crs'

**Comment by ResidentMario** [comment]
That's unusual. This is more likely to be an environmental configuration error than a library error.

What version of `geoplot` are you on? You can check this with `pip list`. What happens when you run `python -c "import geoplot"` from the command line?

**Comment by gracethedog** [comment]
geoplot version is 0.3.2. Just installed Geoplot today under anaconda cloud, and also got GeoPandas and Cartopy installed. The python version is 3.6.6

**Comment by gracethedog** [comment]
import geopandas
import geoplot
Traceback (most recent call last):

  File "<ipython-input-6-7cdf243b4a46>", line 2, in <module>
    import geoplot

  File "/anaconda3/envs/myenv/lib/python3.6/site-packages/geoplot/__init__.py", line 1, in <module>
    from .geoplot import (

  File "/anaconda3/envs/myenv/lib/python3.6/site-packages/geoplot/geoplot.py", line 11, in <module>
    import geoplot.crs as gcrs

AttributeError: module 'geoplot' has no attribute 'crs'

**Comment by ResidentMario** [comment]
Interestingly enough, I can't actually reproduce this error.

```python
conda create --name geoplot-test-env python=3.6.6 geoplot --yes
conda activate geoplot-test-env
python -c "import geoplot"
```

Results in a different error:

```python
ImportError: dlopen(/Users/alex/miniconda3/envs/geoplot-test-env/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.76.dylib
  Referenced from: /Users/alex/miniconda3/envs/geoplot-test-env/lib/libgdal.20.dylib
  Reason: image not found
```

There is something funky going on with the `conda` release that I am going to have to debug. Thanks for flagging.

**Comment by ResidentMario** [comment]
I just released a new version of `geoplot`, version `0.4.0`, can you upgrade to `0.4.0` (via e.g. `conda install -U geoplot`), and when you do, does the error persist?

**Comment by gracethedog** [comment]
Did not work. after update, my Matplotlib was removed.

**Comment by ResidentMario** [comment]
I don't really see how it's possible that installing an upgraded version of `geoplot` removed a dependency that is still listed in `geoplot` dependencies. The environment you are using sounds very broken.

**Comment by mym92** [comment]
> import geopandas
> import geoplot
> Traceback (most recent call last):
> 
> File "", line 2, in
> import geoplot
> 
> File "/anaconda3/envs/myenv/lib/python3.6/site-packages/geoplot/**init**.py", line 1, in
> from .geoplot import (
> 
> File "/anaconda3/envs/myenv/lib/python3.6/site-packages/geoplot/geoplot.py", line 11, in
> import geoplot.crs as gcrs
> 
> AttributeError: module 'geoplot' has no attribute 'crs'

The same error. Any solutions?

**Comment by ResidentMario** [comment]
Create a clean conda environment (`conda create --name foo python=3.7`) and then install `geoplot` (`conda install geoplot`). Then run `python -c "import geoplot"`. Does this error persist?

**Comment by mym92** [comment]
> Create a clean conda environment (`conda create --name foo python=3.7`), activate it (`conda activate foo`) and then install `geoplot` (`conda install geoplot`). Then run `python -c "import geoplot"`. Does this error persist?

I updated the Rasterio package and it worked.

**Comment by ResidentMario** [comment]
Hmm. That's weird. What version of `rasterio` were you on previously? What version are you on now? Was `rasterio` the only package that was changed?

**Comment by mym92** [comment]
> Hmm. That's weird. What version of `rasterio` were you on previously? What version are you on now? Was `rasterio` the only package that was changed?

rasterio-1.0b2 to 1.1.2. 
Yes, it is the only one I upadated.

**Comment by ResidentMario** [comment]
OK, that should be enough information for me to debug what's going on here. Thanks!

**Comment by mym92** [comment]
> OK, that should be enough information for me to debug what's going on here. Thanks!

thank you.

**Comment by ResidentMario** [comment]
Closing as stale. Sorry about that!
