### ISSUE TITLE
Cannot plot with projection

### ISSUE THREAD

**Issue by sdayu** [ResidentMario/geoplot#190]
I try to run plotting_with_geoplot.py with available on [](http://geopandas.org/gallery/plotting_with_geoplot.html) in python3.7. The result could not appear but got a message below.  

```
Geometry must be a Point or LineString
python: geos_ts_c.cpp:4038: int GEOSCoordSeq_getSize_r(GEOSContextHandle_t, const geos::geom::CoordinateSequence*, unsigned int*): Assertion `0 != cs' failed.`
```

I use the lasted version of geoplot (0.4.0). Any suggestion?

**Comment by sdayu** [comment]
> I try to run plotting_with_geoplot.py with available on in python3.7. The result could not appear but got a message below.
> 
> `Geometry must be a Point or LineString python: geos_ts_c.cpp:4038: int GEOSCoordSeq_getSize_r(GEOSContextHandle_t, const geos::geom::CoordinateSequence*, unsigned int*): Assertion `0 != cs' failed.`
> I use lasted version of geoplot (0.4.0). Any suggestion?

**Comment by ResidentMario** [comment]
That error message indicates that you were attempting to pass something that was not a point or a linestring object to a plot method that expects points or linestrings. That probably means that the data in your `geometry` column is in an invalid format. What is in the `geometry` column of the dataset you passed to the method, and what `geoplot` method did you try to plot with?

**Comment by sdayu** [comment]
plotting_with_geoplot.py as an example from http://geopandas.org/gallery/plotting_with_geoplot.html . Then, I don't know what wrong in this script.

**Comment by ResidentMario** [comment]
The `plotting_with_geoplot` example has fallen behind, as the `geoplot` API changed in a small but breaking way in the `0.4.0` release. I've gone ahead and submitted [a PR](https://github.com/geopandas/geopandas/pull/1218) fixing the issue. However, that is unrelated to this issue.

Can you create a [minimal complete reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating the issue you are having? And can you provide the output of `pip list` as well as your installed Python version?

**Comment by sdayu** [comment]
I cloned geoplot repository and install in virtual environment with python3-venv, then I ran the plot_nyc_collisions_map in example directory. It also got same as previous result, as shown below.

```
$ python plot_nyc_collisions_map.py
Geometry must be a Point or LineString
python: geos_ts_c.cpp:4038: int GEOSCoordSeq_getSize_r(GEOSContextHandle_t, const geos::geom::CoordinateSequence*, unsigned int*): Assertion `0 != cs' failed.
[1]    222604 abort      python plot_nyc_collisions_map.py
$ pip list
Package         Version     Location                                          
--------------- ----------- --------------------------------------------------
affine          2.3.0       
attrs           19.3.0      
Cartopy         0.17.0      
certifi         2019.9.11   
chardet         3.0.4       
Click           7.0         
click-plugins   1.1.1       
cligj           0.5.0       
contextily      1.0rc2      
cycler          0.10.0      
Deprecated      1.2.7       
descartes       1.1.0       
Fiona           1.8.11      
geographiclib   1.50        
geopandas       0.6.2       
geoplot         0.4.0       /tmp/test-plot/dev-env/lib/python3.7/site-packages
geopy           1.20.0      
idna            2.8         
joblib          0.14.0      
kiwisolver      1.1.0       
mapclassify     2.1.1       
matplotlib      3.1.1       
mercantile      1.1.2       
munch           2.5.0       
numpy           1.17.4      
pandas          0.25.3      
Pillow          6.2.1       
pip             18.1        
pkg-resources   0.0.0       
pyparsing       2.4.5       
pyproj          2.4.1       
pyshp           2.1.0       
python-dateutil 2.8.1       
pytz            2019.3      
rasterio        1.1.1       
requests        2.22.0      
scikit-learn    0.21.3      
scipy           1.3.2       
seaborn         0.9.0       
setuptools      40.8.0      
Shapely         1.6.4.post2 
six             1.13.0      
snuggs          1.4.7       
urllib3         1.25.7      
wrapt           1.11.2  
```

**Comment by ResidentMario** [comment]
I see. I can run that script locally on my machine no problem, which confirms that this is an issue with your environment. 

The geospatial Python stack has some very finicky requirements around the linking of GEOS versions, which have caused innumerable problems in the past. TLDR: two different libraries in the set of libraries you've installed and which `geoplot` depends are compatible with two different versions of GEOS, but your environment is linking both to the same version, causing everything to break as soon as it gets to C land. Installation using `pip` and `virtualenv` is unfortunately very flaky as a result, and I don't provide any guarantees that it will work (and indeed it does not here).

The [Installation section of the documentation](https://residentmario.github.io/geoplot/installation.html) instead documents that installation *is only supported* via `conda`. This is unfortunate, but made necessary by this dependency bugbear.

You should switch to installing `geoplot` using the `conda` tool instead.

**Comment by ResidentMario** [comment]
Closing this issue now as a CANTFIX. Let me know if you run into any issues installing using `conda`.
