### ISSUE TITLE
How does Webmap show its edge?

### ISSUE THREAD

**Issue by dickwxyz** [ResidentMario/geoplot#191]
```
import geoplot as gplt 
import geoplot.crs as gcrs   
import geopandas as gpd   
boroughs = gpd.read_file(gplt.datasets.get_path('nyc_boroughs'))
gplt.webmap(boroughs, projection=gcrs.WebMercator())
```

I want to show the edge in the Webmap().
But `gplt.webmap(boroughs, projection=gcrs.WebMercator(),edgecolor='black')` does not work.
Thank you for your help.

**Comment by ResidentMario** [comment]
I don't understand what you expect the behavior to be in this case.

`edgecolor` is a `matplotlib` parameter that changes the edge color of whatever mark you are using. `webmap` outputs webmap tiles, *not* points or polygons of any kind. There are no meaningful edges in a webmap.

**Comment by ResidentMario** [comment]
If you mean to change the color of the plot frame, e.g. its bounding box, see this SO answer: https://stackoverflow.com/questions/7778954/elegantly-changing-the-color-of-a-plot-frame-in-matplotlib

**Comment by dickwxyz** [comment]
I want to show the linestrings of `boroughs`, but in the `webmap()` it seems disappeared.

**Comment by ResidentMario** [comment]
You can achieve that using *overplotting* to combine a `webmap` with a `polyplot`:

```
import geoplot.crs as gcrs
import geoplot as gplt

ax = gplt.webmap(boroughs, projection=gcrs.WebMercator())
gplt.polyplot(boroughs, zorder=1, ax=ax)
```

By default `polyplot` has a `zorder` of `-1`, so it will appear below any other plot type by default. You will need to adjust the `zorder` parameter to place it on top instead, as I've done here.
