### ISSUE TITLE
How to plot LINESTRING geometries?

### ISSUE THREAD

**Issue by saadsaifse** [ResidentMario/geoplot#204]
I have some dataset that only contains LINESTRING type geometries. I see in the plots reference that we can plot points and polygonal geometry data among others [here](https://residentmario.github.io/geoplot/plot_references/plot_reference.html)  but how do we draw LINESTRING only data? There is no function in the library as well for this.

**Comment by ResidentMario** [comment]
The Sankey plot type solves for this ask:

> A basic sankey requires a GeoDataFrame of LineString or MultiPoint
geometries.
