### ISSUE TITLE
Overplotting on choropleth

### ISSUE THREAD

**Issue by etrevis** [ResidentMario/geoplot#206]
I am having issue overplotting on top of a choropleth:

```
fig = plt.figure(figsize=(12,16), dpi=150,constrained_layout=True)
gs = fig.add_gridspec(2,3,**{'height_ratios': [4,1], 'hspace':0.1, 'wspace': 0.3  })
ax1 = fig.add_subplot(gs[0,:], projection=gcrs.EuroPP())

gplt.choropleth(geodataframe,                    
                    ax=ax1,
                    extent = extent, 
                    figsize = (12,12),
                    hue='a_random_label',
                    cmap=cmap.cmap, #previously defined
                    norm = norm,  #previously defined
                    edgecolor='black',
                    linewidth=0.6,
                   )
gplt.polyplot(another_geodataframe, ax=ax1, extent = extent, edgecolor='red', linewidth=10)
```

The red polygon(s) are covered by the other map. If I comment/remove the choropleth call I see them. 
Is this an expected behaviour? 

With choropleth:
![image](https://user-images.githubusercontent.com/16451399/76455804-64972680-63d6-11ea-8527-89713040852c.png)

whithout choropleth:
![image](https://user-images.githubusercontent.com/16451399/76455944-91e3d480-63d6-11ea-8510-63de19a1ea87.png)

**Comment by ResidentMario** [comment]
Hi, I believe that by default `polyplot` will appear below any other plot in the plot order. You can adjust this behavior using the `zorder` parameter, e.g. setting `zorder=2` or `zorder=100` or something should do the trick.

I believe this behavior has been changed in the current version of `geoplot` on `master`, but this has not been released yet.

**Comment by etrevis** [comment]
@ResidentMario Thanks for the quick and precise reply.

I think that changing it was a good choice, while it can be avoided easily it is quite counter-intuitive and generates confusion if not well documented.
