### ISSUE TITLE
what does clip in kdeplot take?

### ISSUE THREAD

**Issue by gauteh** [ResidentMario/geoplot#209]
Hi,

I'm trying to do a kdeplot of points in the ocean. Naturally the heatmap extends onto land. I want to clip this away using e.g. the shapes from cartopy.feature.LAND or coastline or similar. Whenever I pass in a shape (multipolygon) I get an error about mismatching number of values (there is not the same amount of polygons as rows I am trying to plot). From the boroughs example I see that this is not necessary, but how are they associated. And how can I do this with one giant shape (the ocean)?

Thanks for this package!

**Comment by ResidentMario** [comment]
I don't know off the top of my head what you might be doing wrong, but if you can post a simple reproducible code sample here demonstrating the issue, maybe I can be helpful in debugging it.
