### ISSUE TITLE
Error importing geopandas

### ISSUE THREAD

**Issue by mtlberri** [ResidentMario/geoplot#210]
I tried to install geoplot in various different ways but can never get rid of errors.

I first tried to create a conda venv from scratch and install: conda install geoplot -c conda-forge
I open a Jupyter Notebook, go through your quick start and get stuck at the very beginning when importing geopandas.

Thinking that this was an issur vith my venv, I decided to completely clone your github repo ResidentMario/geoplot and creata a brand new environment from your environment.yml. I did that, and run my Jupyter Notebook from that geoplot-dev venv: I still cannot import geopandas without error.

That is strange, I have no clue on how to get set-up and use geoplot at that point. Would be glad if you can help.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a62d01c1d62e> in <module>
----> 1 import geopandas as gpd

~/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/geopandas/__init__.py in <module>
      3 from geopandas.array import _points_from_xy as points_from_xy  # noqa
      4 
----> 5 from geopandas.io.file import read_file  # noqa
      6 from geopandas.io.sql import read_postgis  # noqa
      7 from geopandas.tools import sjoin  # noqa

~/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/geopandas/io/file.py in <module>
      4 import pandas as pd
      5 
----> 6 import fiona
      7 from shapely.geometry import mapping
      8 from shapely.geometry.base import BaseGeometry

~/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/fiona/__init__.py in <module>
     82     os.environ["PATH"] = os.environ["PATH"] + ";" + libdir
     83 
---> 84 from fiona.collection import BytesCollection, Collection
     85 from fiona.drvsupport import supported_drivers
     86 from fiona.env import ensure_env_with_credentials, Env

~/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/fiona/collection.py in <module>
      7 
      8 from fiona import compat, vfs
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: dlopen(/Users/Armellini1/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): Library not loaded: @rpath/libnetcdf.15.dylib
  Referenced from: /Users/Armellini1/opt/anaconda3/envs/geoplot-dev/lib/libgdal.26.dylib
  Reason: image not found

**Comment by ResidentMario** [comment]
Can you trying `conda install geopandas -c conda-forge`, seeing if that works, then following up with `conda install geopandas` and seeing if everything still works then?

**Comment by jGaboardi** [comment]
We are having issues with `geopandas` today as well. See pysal/libpysal#271, specifically [this comment](https://github.com/pysal/libpysal/issues/271#issuecomment-605730239). Seems to be another `libgdal` issue.

**Comment by mtlberri** [comment]
Ok so I did as you asked: install geopandas and then try import. But error again. Ref. below 

(geoplot-dev) Joffreys-MBP:geoplot Armellini1$ conda install geopandas -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/Armellini1/opt/anaconda3/envs/geoplot-dev

  added / updated specs:
    - geopandas


The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2019.11.28-hecc5488_0
  certifi              pkgs/main::certifi-2019.11.28-py38_1 --> conda-forge::certifi-2019.11.28-py38h32f6830_1
  openssl              pkgs/main::openssl-1.1.1e-h1de35cc_0 --> conda-forge::openssl-1.1.1e-h0b31af3_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(geoplot-dev) Joffreys-MBP:geoplot Armellini1$ 

(geoplot-dev) Joffreys-MBP:geoplot Armellini1$ python -c "import geopandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Armellini1/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/geopandas/__init__.py", line 5, in <module>
    from geopandas.io.file import read_file  # noqa
  File "/Users/Armellini1/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/geopandas/io/file.py", line 6, in <module>
    import fiona
  File "/Users/Armellini1/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/fiona/__init__.py", line 84, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/Users/Armellini1/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/Armellini1/opt/anaconda3/envs/geoplot-dev/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): Library not loaded: @rpath/libnetcdf.15.dylib
  Referenced from: /Users/Armellini1/opt/anaconda3/envs/geoplot-dev/lib/libgdal.26.dylib
  Reason: image not found
(geoplot-dev) Joffreys-MBP:geoplot Armellini1$

**Comment by ResidentMario** [comment]
Not your fault, it looks like there's an error in the `geopandas` feedstock again due to the shifting sand of C dependencies.

**Comment by mtlberri** [comment]
Hmm ok I see. Thanks for letting me know. What should I do in your view? Is there a way to install a previous version of geopandas with conda? (would that solve the issue?)

**Comment by ResidentMario** [comment]
For now you can try `pip install geopandas` followed by `conda install geoplot`. I've reported the issue in the `geopandas` gitter channel here: https://gitter.im/geopandas/geopandas.

**Comment by mtlberri** [comment]
I tried (uninstalled geopandas from my venv, installed it back with pip, then conda geoplot). But I still get an error when importing geopandas.
Ok no big deal, I will wait for the geopandas issue to be fixed. Thanks for having looked into it!

**Comment by jorisvandenbossche** [comment]
`pip install geopandas` won't help if the dependencies of geopandas were installed with conda (since it is not the geopandas build that is broken, but one of its dependencies, i.e. fiona).

I think it is the same issue as the one already reported (https://github.com/conda-forge/fiona-feedstock/issues/159), and you can temporally pin libnetcdf:

```
conda create -n test_env geopandas libnetcdf=4.7.3
```

**Comment by ResidentMario** [comment]
This has been fixed downstream (see the gitter and/or the issue link joris provided) and you should be able to install `geoplot` again the normal way.

**Comment by mtlberri** [comment]
Thank you both, I tried and it was fixed.
I am all set-up to use geoplot! Thanks for the support.
