### ISSUE TITLE
AttributeError: module 'geoplot' has no attribute 'datasets'

### ISSUE THREAD

**Issue by MatthiVH** [ResidentMario/geoplot#212]
Hi there,

From the following website (https://geopandas.org/gallery/plotting_with_geoplot.html), I wanted to test the example Python file.

For some reason I get an AttributeError: module 'geoplot' has no attribute 'datasets'. 
Any idea why this happens? Something to be fixed?

**Comment by ResidentMario** [comment]
Works on my machine. Make sure you're running version 0.3.0 or higher, see #164.
