### ISSUE TITLE
Customizing colorbar label font size

### ISSUE THREAD

**Issue by stcoats** [ResidentMario/geoplot#213]
I would like to have a colorbar with a larger font and larger tick labels, for example in a plot like this: 

```
fig, ax = plt.subplots( )
geoplot.choropleth(
        df, projection = gcrs.EuroPP(), hue= df["density"], cmap='Reds', 
            figsize=(18,18), legend = True, 
                   ax = ax,
                   legend_kwargs = {'shrink' : 0.5,
                                   'label':'Values',
                                    'aspect':10,
                                   'spacing':'proportional',
                                   })
```
How can I do that?

**Comment by ResidentMario** [comment]
Unfortunately it looks like `matplotlib` makes this a lot harder to do than it needs to be. I'd expect this to be a settable property on the colorbar object, which you can pass to using `legend_kwargs` (as you already are), but instead it looks like [you're going to have to manipulate the colorbar object directly](https://stackoverflow.com/questions/23172282/how-to-change-font-properties-of-a-matplotlib-colorbar-label).

I don't have any advice that's better than that unfortunately, sorry. Let me know what your solution is, if you come up with one&mdash;I'm sure your answer will be useful to future visitors/users of this repo!
