### ISSUE TITLE
Error when calling geoplot.crs.UTM()

### ISSUE THREAD

**Issue by kahyforest** [ResidentMario/geoplot#215]
geoplot uses cartopy's projections. According to the cartopy documentations, crs.UTM has 1 mandatory argument, the zone:

> class cartopy.crs.UTM(zone, southern_hemisphere=False, globe=None)

When I use geoplot to create UTM projection for zone 33 that I will later assign to a plot, I get the following error:

```
import geoplot as gplt
UTM_proj = gplt.crs.UTM(33)

TypeError: __init__() takes 1 positional argument but 2 were given
```
conda info:

>      active environment : kari_env
>     active env location : C:\Program Files\Miniconda3\envs\kari_env
>        shell level : 2
>        user config file : C:\Users\kahy\.condarc
>       populated config files : C:\Users\kahy\.condarc
>        conda version : 4.8.3
>       conda-build version : 3.18.11
>        python version : 3.7.6.final.0
>        virtual packages :
>        base environment : C:\Program Files\Miniconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/win-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/win-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/msys2/win-64
>                           https://repo.anaconda.com/pkgs/msys2/noarch
>           package cache : C:\Program Files\Miniconda3\pkgs
>                           C:\Users\kahy\.conda\pkgs
>                           C:\Users\kahy\AppData\Local\conda\conda\pkgs
>        envs directories : C:\Program Files\Miniconda3\envs
>                           C:\Users\kahy\.conda\envs
>                           C:\Users\kahy\AppData\Local\conda\conda\envs
>                platform : win-64
>              user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
>           administrator : True
>              netrc file : None
>            offline mode : False

conda list:

> # Name                    Version                   Build  Channel
> affine                    2.3.0                      py_0    conda-forge
> alabaster                 0.7.12                     py_0
> argh                      0.26.2                   py38_0
> astroid                   2.4.0                    py38_0
> atomicwrites              1.4.0                      py_0
> attrs                     19.3.0                     py_0    conda-forge
> autopep8                  1.4.4                      py_0
> babel                     2.8.0                      py_0
> backcall                  0.1.0                    py38_0
> bcrypt                    3.1.7            py38he774522_0
> blas                      1.0                         mkl
> bleach                    3.1.4                      py_0
> boost-cpp                 1.72.0               h0caebb8_0    conda-forge
> bzip2                     1.0.8                hfa6e2cd_2    conda-forge
> ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
> cartopy                   0.18.0           py38h4990f70_0    conda-forge
> certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
> cffi                      1.14.0           py38h7a1dbc1_0
> cfitsio                   3.470                he774522_5    conda-forge
> chardet                   3.0.4                 py38_1003
> click                     7.1.2              pyh9f0ad1d_0    conda-forge
> click-plugins             1.1.1                      py_0    conda-forge
> cligj                     0.5.0                      py_0    conda-forge
> cloudpickle               1.4.1                      py_0
> colorama                  0.4.3                      py_0
> contextily                1.0.0                      py_0    conda-forge
> cryptography              2.9.2            py38h7a1dbc1_0
> curl                      7.69.1               h1dcc11c_0    conda-forge
> cycler                    0.10.0                   py38_0
> decorator                 4.4.2                      py_0
> defusedxml                0.6.0                      py_0
> deprecated                1.2.10             pyh9f0ad1d_0    conda-forge
> descartes                 1.1.0                      py_4
> diff-match-patch          20181111                   py_0
> docutils                  0.16                     py38_0
> entrypoints               0.3                      py38_0
> expat                     2.2.9                he025d50_2    conda-forge
> fiona                     1.8.13           py38h41bf4fa_1    conda-forge
> flake8                    3.7.9                    py38_0
> freetype                  2.9.1                ha9979f8_1
> freexl                    1.0.5             hd288d7e_1002    conda-forge
> future                    0.18.2                   py38_0
> gdal                      3.0.4            py38h3ba59e7_9    conda-forge
> geographiclib             1.50                       py_0    conda-forge
> geopandas                 0.7.0                      py_1    conda-forge
> geoplot                   0.4.0                      py_1    conda-forge
> geopy                     1.22.0             pyh9f0ad1d_0    conda-forge
> geos                      3.8.1                he025d50_0    conda-forge
> geotiff                   1.5.1               h3d29ae3_10    conda-forge
> gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
> glib                      2.64.2               he4de6d7_0    conda-forge
> hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
> hdf5                      1.10.6          nompi_ha405e13_100    conda-forge
> icc_rt                    2019.0.0             h0cc432a_1
> icu                       64.2                 he025d50_1    conda-forge
> idna                      2.9                        py_1
> imagesize                 1.2.0                      py_0
> importlib_metadata        1.5.0                    py38_0
> intel-openmp              2020.1                      216
> intervaltree              3.0.2                      py_0
> ipykernel                 5.1.4            py38h39e3cac_0
> ipython                   7.13.0           py38h5ca1d4c_0
> ipython_genutils          0.2.0                    py38_0
> isort                     4.3.21                   py38_0
> jedi                      0.15.2                   py38_0
> jinja2                    2.11.2                     py_0
> joblib                    0.14.1                     py_0    conda-forge
> jpeg                      9c                hfa6e2cd_1001    conda-forge
> jsonschema                3.2.0                    py38_0
> jupyter_client            6.1.3                      py_0
> jupyter_core              4.6.3                    py38_0
> kealib                    1.4.13               h3b59ab9_1    conda-forge
> keyring                   21.1.1                   py38_2
> kiwisolver                1.2.0            py38h74a9793_0
> krb5                      1.17.1               hdd46e55_0    conda-forge
> lazy-object-proxy         1.4.3            py38he774522_0
> libclang                  9.0.1           default_hf44288c_0    conda-forge
> libcurl                   7.69.1               h1dcc11c_0    conda-forge
> libffi                    3.2.1             h6538335_1007    conda-forge
> libgdal                   3.0.4                h6f60a84_9    conda-forge
> libiconv                  1.15              hfa6e2cd_1006    conda-forge
> libkml                    1.3.0             h7e985d0_1011    conda-forge
> libnetcdf                 4.7.4           nompi_h256d12c_104    conda-forge
> libpng                    1.6.37               h2a8f88b_0
> libpq                     12.2                 hd9aa61d_1    conda-forge
> libsodium                 1.0.16               h9d3ae62_0
> libspatialindex           1.9.3                he025d50_3    conda-forge
> libspatialite             4.3.0a            h51df0ed_1038    conda-forge
> libssh2                   1.8.2                h642c060_2    conda-forge
> libtiff                   4.1.0                h885aae3_6    conda-forge
> libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
> libxml2                   2.9.10               h5d81f1c_1    conda-forge
> libxslt                   1.1.33               h579f668_1    conda-forge
> lz4-c                     1.9.2                h62dcd97_1    conda-forge
> m2w64-expat               2.1.1                         2
> m2w64-gcc-libgfortran     5.3.0                         6
> m2w64-gcc-libs            5.3.0                         7
> m2w64-gcc-libs-core       5.3.0                         7
> m2w64-gettext             0.19.7                        2
> m2w64-gmp                 6.1.0                         2
> m2w64-libiconv            1.14                          6
> m2w64-libwinpthread-git   5.0.0.4634.697f757               2
> m2w64-xz                  5.2.2                         2
> mapclassify               2.2.0                      py_0    conda-forge
> markupsafe                1.1.1            py38he774522_0
> matplotlib                3.1.3                    py38_0
> matplotlib-base           3.1.3            py38h64f37c6_0
> mccabe                    0.6.1                    py38_1
> mercantile                1.1.4              pyh9f0ad1d_0    conda-forge
> mistune                   0.8.4           py38he774522_1000
> mkl                       2020.1                      216
> mkl-service               2.3.0            py38hb782905_0
> mkl_fft                   1.0.15           py38h14836fe_0
> mkl_random                1.1.0            py38hf9181ef_0
> msys2-conda-epoch         20160418                      1
> munch                     2.5.0                      py_0    conda-forge
> nbconvert                 5.6.1                    py38_0
> nbformat                  5.0.6                      py_0
> numpy                     1.18.1           py38h93ca92e_0
> numpy-base                1.18.1           py38hc3f5095_1
> numpydoc                  0.9.2                      py_0
> olefile                   0.46                       py_0    conda-forge
> openjpeg                  2.3.1                h57dd2e7_3    conda-forge
> openssl                   1.1.1g               he774522_0    conda-forge
> owslib                    0.19.2                     py_1    conda-forge
> packaging                 20.3                       py_0
> pandas                    1.0.3            py38h47e9c7a_0
> pandoc                    2.2.3.2                       0
> pandocfilters             1.4.2                    py38_1
> paramiko                  2.7.1                      py_0
> parso                     0.5.2                      py_0
> pathtools                 0.1.2                      py_1
> patsy                     0.5.1                      py_0    conda-forge
> pcre                      8.44                 h6538335_0    conda-forge
> pexpect                   4.8.0                    py38_0
> pickleshare               0.7.5                 py38_1000
> pillow                    7.1.2            py38h7011068_0    conda-forge
> pip                       20.0.2                   py38_3
> pluggy                    0.13.1                   py38_0
> poppler                   0.87.0               h0cd1227_1    conda-forge
> poppler-data              0.4.9                         1    conda-forge
> postgresql                12.2                 he14cc48_1    conda-forge
> proj                      7.0.0                haa36216_3    conda-forge
> prompt-toolkit            3.0.4                      py_0
> prompt_toolkit            3.0.4                         0
> psutil                    5.7.0            py38he774522_0
> pycodestyle               2.5.0                    py38_0
> pycparser                 2.20                       py_0
> pydocstyle                4.0.1                      py_0
> pyepsg                    0.4.0                      py_0    conda-forge
> pyflakes                  2.1.1                    py38_0
> pygments                  2.6.1                      py_0
> pylint                    2.5.0                    py38_1
> pynacl                    1.3.0            py38h62dcd97_0
> pyopenssl                 19.1.0                   py38_0
> pyparsing                 2.4.7                      py_0
> pyproj                    2.6.1.post1      py38h1dd9442_0    conda-forge
> pyqt                      5.12.3           py38h7ae7562_3    conda-forge
> pyqt5-sip                 4.19.18                  pypi_0    pypi
> pyqtchart                 5.12                     pypi_0    pypi
> pyqtwebengine             5.12.1                   pypi_0    pypi
> pyrsistent                0.16.0           py38he774522_0
> pyshp                     2.1.0                      py_0    conda-forge
> pyside2                   5.13.2           py38hfa7ce6d_2    conda-forge
> pysocks                   1.7.1                    py38_0
> python                    3.8.2               he1778fa_13
> python-dateutil           2.8.1                      py_0
> python-jsonrpc-server     0.3.4                      py_0
> python-language-server    0.31.10                  py38_0
> python_abi                3.8                      1_cp38    conda-forge
> pytz                      2020.1                     py_0
> pywin32                   227              py38he774522_1
> pywin32-ctypes            0.2.0                 py38_1000
> pyyaml                    5.3.1            py38he774522_0
> pyzmq                     18.1.1           py38ha925a31_0
> qdarkstyle                2.8.1                      py_0
> qt                        5.12.5               h7ef1ec2_0    conda-forge
> qtawesome                 0.7.0                      py_0
> qtconsole                 4.7.4                      py_0
> qtpy                      1.9.0                      py_0
> rasterio                  1.1.3            py38h2617b1b_0    conda-forge
> rasterstats               0.14.0                     py_0    conda-forge
> requests                  2.23.0                   py38_0
> rope                      0.17.0                     py_0
> rtree                     0.9.4            py38h7ad75cc_1    conda-forge
> scikit-learn              0.22.1           py38h6288b17_0
> scipy                     1.4.1            py38h9439919_0
> seaborn                   0.10.1                     py_0
> setuptools                46.2.0                   py38_0
> shapely                   1.7.0            py38hbf43935_3    conda-forge
> simplejson                3.17.0           py38h9de7a3e_1    conda-forge
> sip                       4.19.13          py38ha925a31_0
> six                       1.14.0                   py38_0
> snowballstemmer           2.0.0                      py_0
> snuggs                    1.4.7                      py_0    conda-forge
> sortedcontainers          2.1.0                    py38_0
> sphinx                    3.0.3                      py_0
> sphinxcontrib-applehelp   1.0.2                      py_0
> sphinxcontrib-devhelp     1.0.2                      py_0
> sphinxcontrib-htmlhelp    1.0.3                      py_0
> sphinxcontrib-jsmath      1.0.1                      py_0
> sphinxcontrib-qthelp      1.0.3                      py_0
> sphinxcontrib-serializinghtml 1.1.4                      py_0
> spyder                    4.1.3                    py38_0
> spyder-kernels            1.9.1                    py38_0
> sqlite                    3.31.1               h2a8f88b_1
> statsmodels               0.11.1           py38h9de7a3e_1    conda-forge
> tbb                       2018.0.5             he980bc4_0
> testpath                  0.4.4                      py_0
> tiledb                    1.7.7                h0b90766_1    conda-forge
> tk                        8.6.10               hfa6e2cd_0    conda-forge
> toml                      0.10.0             pyh91ea838_0
> tornado                   6.0.4            py38he774522_1
> traitlets                 4.3.3                    py38_0
> ujson                     1.35             py38he774522_0
> urllib3                   1.25.8                   py38_0
> vc                        14.1                 h0510ff6_4
> vs2015_runtime            14.16.27012          hf0eaf9b_1
> watchdog                  0.10.2                   py38_0
> wcwidth                   0.1.9                      py_0
> webencodings              0.5.1                    py38_1
> wheel                     0.34.2                   py38_0
> win_inet_pton             1.1.0                    py38_0
> wincertstore              0.2                      py38_0
> wrapt                     1.11.2           py38he774522_0
> xerces-c                  3.2.2             h6538335_1004    conda-forge
> xlrd                      1.2.0                      py_0
> xz                        5.2.5                h2fa13f4_0    conda-forge
> yaml                      0.1.7                hc54c509_2
> yapf                      0.28.0                     py_0
> zeromq                    4.3.1                h33f27b4_3
> zipp                      3.1.0                      py_0
> zlib                      1.2.11               h62dcd97_4
> zstd                      1.4.4                h9f78265_3    conda-forge

**Comment by ResidentMario** [comment]
Hi, thanks for reporting! This does look like a bug, but I'm generally genuinely not sure how well `geoplot` supports some of the more exotic projection types in general. I'd like to improve on CRS reuse and robustness in general, but the `cartopy` documentation on this subject is very light on the details, so it may take some time before that actually happens.

**Comment by kahyforest** [comment]
Ok, thanks for the reply. The issue might be linked to some of the other issues about working with cartesian coordinates, e.g:

https://gis.stackexchange.com/questions/361881/geoplot-axis-limits-cannot-be-nan-or-inf

**Comment by skytwosea** [comment]
@kahyforest @ResidentMario Just writing to confirm identical behaviour. Also running miniconda envs, on Ubuntu 19.10. The NAN issue you linked was mine; the original problem was solved (rookie pandas user here - there actually were some Nan values in my source data... derp), but then my problems morphed into this UTM projection issue.

**Comment by ResidentMario** [comment]
I've removed `UTM` from the projects list for now. It looks like you are right, it's always required a `zone` parameter and has always been broken as a consequence. `geoplot` shouldn't have claimed to support it in the first place, apologies!

If you really need the UTM project for your specific use case, I'd suggest submitting a PR for it. Adding and testing a new projection is not really something I can prioritize or have the time budget for right now. 😅
