### ISSUE TITLE
geoplot's kdeplot method kernel change problem ~ 

### ISSUE THREAD

**Issue by yongjinkim92** [ResidentMario/geoplot#222]
Thank u for geoplot :)

Now we experiment some geo-data. 

we wanna change kdeplot's kernel, but didn't change the kernel.... always same graph
(ex: we wanna change 'gaussian' to 'triweight' )

our code is below..

![image](https://user-images.githubusercontent.com/57974425/82729201-898e0b00-9d30-11ea-8309-8a10d76d56f9.png)

our code have any problem?

**Comment by ResidentMario** [comment]
Hi, thanks for reporting this issue!

Yes, this parameter _should_ be getting passed down to the underlying `seaborn` method, but at a glance that might indeed not be happening. Bummer!

**Comment by ResidentMario** [comment]
This is now fixed. Funnily enough, `seaborn` has dropped support for non-Gaussian kernels:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/3466341/155897230-41842061-06f4-42c4-8ae2-2c507013b954.png">
