### ISSUE TITLE
choropleth ignores missing values?

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [ResidentMario/geoplot#224]
Hi there, I am plotting a column that has missing values. GEOPANDAS gives no color to missing values, but GEOPLOT.CHOROPLETH does... is there any way I can control the color for missingness?

**Comment by ResidentMario** [comment]
Plotting with a transparent fill by default in this case would be a good feature, yeah.

There's no way to control the color of the empty geometry (besides direct manipulation of the plot after-the-fact). For now I would recommend excluding those records from plotting by using [`dropna`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html) on the `GeoDataFrame` beforehand.

**Comment by ResidentMario** [comment]
#230 is another example of `sns.kdeplot` mysteriously ignoring passed-through parameters.
