### ISSUE TITLE
kdelot warning - error

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [ResidentMario/geoplot#227]
Why this code:
![image](https://user-images.githubusercontent.com/7110381/87001421-00665280-c17d-11ea-8c48-7af59999ba77.png)
keeps giving me this?
![image](https://user-images.githubusercontent.com/7110381/87001466-1f64e480-c17d-11ea-81e3-c9767d524c9d.png)

The plot works, and I have plotted all the other elements with no problem before.

Thanks!

**Comment by ResidentMario** [comment]
This is a future warning about a forthcoming depreciation issue in
geopandas. Is it possible you are not on the latest version of geoplot? I
had thought I had fixed this in a previous release...but maybe not.

**Comment by ResidentMario** [comment]
This was fixed in an earlier release.
