### ISSUE TITLE
Will kdeplot() update with seaborn 0.11.0 

### ISSUE THREAD

**Issue by CNFeffery** [ResidentMario/geoplot#228]
I noticed that seaborn updated to 0.11 recently, then its `kdeplot()` support weighted kernel density via parameter `weights`, will `geoplot` update its `kdeplot` in the future too🤔, I think this is a very useful feature.
![image](https://user-images.githubusercontent.com/49147660/93040265-2415af80-f67c-11ea-8f7f-1669e0e0114a.png)

**Comment by ResidentMario** [comment]
I believe that the relevant bug, where the parameter was not being passed down to the underlying `seaborn.kdeplot`, has now been fixed.
