### ISSUE TITLE
Missing Cartopy projections (and suggestion)

### ISSUE THREAD

**Issue by mangecoeur** [ResidentMario/geoplot#232]
Hi, it's suggested in the docs that Cartopy projections are supported but it seems the Eckert 1-6 set are missing. Not sure if this is trivial to add or not.

As an API suggestion, perhaps geoplot should directly accept cartopy CRS objects and convert them internally (and eventually do the same for raw proj4 CRS objects, which look like they may be supported in cartopy at some point). Otherwise we end up with a mess of incompatible CRS object types (geoplot, cartopy, proj4). This would become especially annoying when working with a mix of plain Cartopy plots and geoplot plots, you need to keep track of different CRS objects for each plot type.

**Comment by ResidentMario** [comment]
Adding Eckert is trivial and has now been done.

I hear you, but. I do not want to manipulate the CRS part of this library any further, to be honest it's a miracle it works right now as it is.

The manner in which `cartopy` projections work (and the variety of errors messages I get from them) is pretty mysterious to me, and I won't have the time or energy budget to deep dive that library anytime soon.
