### ISSUE TITLE
BUG: Voronoi broken with GeoPandas using pygeos

### ISSUE THREAD

**Issue by martinfleis** [ResidentMario/geoplot#234]
`voronoi` plot is broken with the latest GeoPandas, raising `ValueError: 'data' should be a 1-dimensional array of geometry objects.`. 

The reason is that below, you pass `geometry=self.set_clip(gpd.GeoDataFrame(geometry=geoms)).values`, which is essentially `geometry=gdf.values`, so you're passing whole GeoDataFrame to a GeoSeries constructor. I know that it worked before and I was thinking if it is a regression on geopandas side or not and I am leaning towards no. We always had a check for dimensions and this case somehow slipped before.

My suggestion would be to pass a GeometryArray instead: `geometry=self.set_clip(gpd.GeoDataFrame(geometry=geoms)).geometry.values`

https://github.com/ResidentMario/geoplot/blob/bdffcd6763b8c948ce4d0308855a4df7ef9b7f1e/geoplot/geoplot.py#L1628-L1630

Code to reproduce the issue (from examples):

```py
import geopandas as gpd
import geoplot as gplt
import geoplot.crs as gcrs
import pandas as pd
import matplotlib.pyplot as plt

melbourne = gpd.read_file(gplt.datasets.get_path('melbourne'))
melbourne_primary_schools = gpd.read_file(gplt.datasets.get_path('melbourne_schools'))\
    .query('School_Type == "Primary"')


ax = gplt.voronoi(
    melbourne_primary_schools, clip=melbourne, linewidth=0.5, edgecolor='white',
    projection=gcrs.Mercator()
)
gplt.polyplot(melbourne, edgecolor='None', facecolor='lightgray', ax=ax)
gplt.pointplot(melbourne_primary_schools, color='black', ax=ax, s=1, extent=melbourne.total_bounds)
plt.title('Primary Schools in Greater Melbourne, 2018')

**Comment by martinfleis** [comment]
Hmm, it probably is GeoPandas issue after all. It works without pygeos and raises an error with pygeos. I'll investigate.

**Comment by ResidentMario** [comment]
Is this bug still live? I rendered the example plot with and without `pygeos` installed, and it worked both times. I have `pygeos==0.10` FYI.

**Comment by ResidentMario** [comment]
Closing for now, since I can't repro.

**Comment by martinfleis** [comment]
The original geopandas bug geopandas/geopandas#1866 is still there. I don't have geoplot in my env to test it (and it wants to downgrade a lot of other packages if I want to install it).
