### ISSUE TITLE
webmap() + polyplot() does not seem to work

### ISSUE THREAD

**Issue by gregorhuh** [ResidentMario/geoplot#237]
Hi there,

first of all congrats on a great product. I'm trying to get `webmap()` to work in conjunction with `polyplot()` but can't seem to get the polys to show. Without `webmap()`, this works no problem:

```
ax = gplt.polyplot(gdf1, extent=extent, projection=gcrs.Mercator(), **kwargs)
gplt.polyplot(gdf2, ax=ax, **kwargs)
```

If I try this with `webmap()`, however, the basemap shows (with the right zoom level and extent), but the polys don't. 

```
ax = gplt.webmap(gdf1, extent=extent, projection=gcrs.WebMercator(), **kwargs)
gplt.polyplot(gdf2, ax=ax, **kwargs)
```

All examples in the documentation use `webmap()` in conjunction with `pointplot()` only. Is that the issue? All my GDFs are in lon lat as required by geoplot, by the way.

Cheers!

**Comment by ResidentMario** [comment]
Hey, sounds like what might be a bug with the ordering of the elements. Can you try changing the `zorder` of the `polyplot`, to see if that helps?

**Comment by gregorhuh** [comment]
That was it! Thanks a million. For some reason, the GDF in the positional argument to `webmap()` refuses stubbornly to be drawn, meaning I have to add it a second time with `polyplot()` (though the documentation suggests one can add and style any GDF as that argument to `webmap()`):

```
ax = gplt.webmap(gdf1, extent=extent, projection=gcrs.WebMercator(), **kwargs)
gplt.polyplot(gdf1, ax=ax, zorder=2, **kwargs)
gplt.polyplot(gdf2, ax=ax, zorder=1, **kwargs)
```
But in either case, I'm happy I got it to work!

Thanks again

**Comment by ResidentMario** [comment]
The PR I just landed should fix this issue out of the box.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/3466341/124367645-248d3000-dc27-11eb-88af-b2f1a61eaad7.png">
