### ISSUE TITLE
Update conda-forge to release 0.4.3?

### ISSUE THREAD

**Issue by jucor** [ResidentMario/geoplot#246]
Thanks @ResidentMario  for a great package, and for adding `NearviewPerspective` to 0.4.3 :) I was precisely looking for it yesterday night!
Any idea how to help conda-forge get up to speed on that new release? It's still [shipping 0.4.1](https://anaconda.org/conda-forge/geoplot), not 0.4.3 yet. Thanks!

**Comment by ResidentMario** [comment]
It's unclear (to me) why the bot that usually handles this sort of thing hasn't minted a new PR to the `geoplot-feedstock` pulling in the update. It's been 24 hours so I've asked about it in the `conda-forge` gitter.

**Comment by jucor** [comment]
Thanks Aleksey!

**Comment by ResidentMario** [comment]
Neglected to close this issue out. It turned to be because `conda` requires a source distribution, and the method I used to push to PyPI initially only pushed a wheel. [Comment there here in `gitter`](https://gitter.im/conda-forge/conda-forge.github.io?at=60e32cdc8c12474d8ced2bb3), for posterity.

**Comment by jucor** [comment]
Awesome, thanks @ResidentMario !
