### ISSUE TITLE
Pin geopandas version?

### ISSUE THREAD

**Issue by jsta** [ResidentMario/geoplot#249]
With geopandas 0.7.0 I get the following error:

```python
import geoplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\vote\lib\site-packages\geoplot\__init__.py", line 1, in <module>
    from .geoplot import (
  File "C:\ProgramData\Anaconda3\envs\vote\lib\site-packages\geoplot\geoplot.py", line 16, in <module>
    from geopandas.plotting import _PolygonPatch as GeopandasPolygonPatch
ImportError: cannot import name '_PolygonPatch' from 'geopandas.plotting' (C:\ProgramData\Anaconda3\envs\vote\lib\site-packages\geopandas\plotting.py)
```

Looks like geopandas > v0.8.1 is needed here

**Comment by ResidentMario** [comment]
Yeah this is a bit if technical debt I need to get around to fixing. Sorry to hear that it bit you. 😢

**Comment by ResidentMario** [comment]
I've minted a new release (`0.4.4`) that properly pins `geopandas>0.9.0`. Note that `0.9.0` is the first version of `geopandas` with `descartes` removed (based on https://github.com/geopandas/geopandas/releases and https://github.com/geopandas/geopandas/pull/1677), not `0.8.1`. Sorry for the friction!
