### ISSUE TITLE
Use contextly to allow mapping with webmap tiles

### ISSUE THREAD

**Issue by ResidentMario** [ResidentMario/geoplot#26]
darribas wrote [`contextily`](https://github.com/darribas/contextily), which is an independent library for handling tiles. This would be a really nice feature to incorporate into `geoplot`.

**Comment by pandeazucar** [comment]
I am coding the feature, but I encountered a problem with the projection. Contextily returns an image (ndarray of RGB values) in Web Mercator, and the extent of the map in Spherical Mercator, EPSG 3857.
I am still new to the subject of map projections, but the feature may only work when plotting data in the Mercator projection. 

I am looking into the [rasterio](https://github.com/mapbox/rasterio) documentation to see if I can reproject the tiles into another ndarray and use that as a basemap when the user wants to plot in a different projection.

**Comment by ResidentMario** [comment]
Ah...you're biting off a lot here.

For now, I wouldn't invest too much time in `rasterio`. Unless the basemap is very basic, I expect that the amount of distortion you would see from a re-projection is just too much. That would be a feature that is added down the line: for now, you should just create a pull request with something works in a compatible projection.

The API should be:

`gplt.polyplot(projection=gcrs.Mercator(), webmap=<some webmap input>)`

I admit I haven't put a ton of thought into it, yet. I'm curious what you'll come up with.

**Comment by pandeazucar** [comment]
#48

**Comment by pandeazucar** [comment]
I just submitted the first pull request. It's still a work in progress. #48

**Comment by ResidentMario** [comment]
Closing in favor of #146.

**Comment by ResidentMario** [comment]
Now implemented in #169. 🎉

**Comment by jorisvandenbossche** [comment]
> I am looking into the rasterio documentation to see if I can reproject the tiles into another ndarray and use that as a basemap when the user wants to plot in a different projection.

Note that contextily now supports this to warp the tiles to another CRS that is not EPSG:3857, see https://contextily.readthedocs.io/en/latest/warping_guide.html

(of course, it still depends on your data and the extent of your plot if that will gives a good looking result, as warping the tiles can give an ugly effect when there is a lot of distortion, especially for things like labels)
