### ISSUE TITLE
Fix KDEPlot hue tests

### ISSUE THREAD

**Issue by ResidentMario** [ResidentMario/geoplot#278]
See https://github.com/ResidentMario/geoplot/pull/272#issuecomment-1053926367 for context.

**Comment by QuLogic** [comment]
Any chance you can release a 0.5.1 with these fixed?

**Comment by ResidentMario** [comment]
Do you have something downstream that's relying on these tests passing?

**Comment by QuLogic** [comment]
For packaging, I always run tests to ensure things are working. Otherwise, the update doesn't happen. I guess no-one is asking for it, so there's no pressing need just yet.

**Comment by QuLogic** [comment]
Thanks, that is working everywhere now.
