### ISSUE TITLE
Can't import geoplot on OSX

### ISSUE THREAD

**Issue by yassineAlouini** [ResidentMario/geoplot#29]
I have installed `geoplot` on OSX using `pip`. I have the version `geoplot (0.0.3)`.

When running `import geoplot as gplt`, I have the following error: 

```
SyntaxError: invalid syntax (geoplot.py, line 1641)
```

I have checked the code and have found that an `*args` is passed as a first argument followed by named arguments. 

I have solved the error (by replacing `*args` with `args`) and then I got an error about not finding the `quad` module: `no module named quad`.

Has anyone encountered this error before? Any workaround would be appreciated.

Here are some information about my configuration (obtained using `watermark` library): 

```
2017-03-09 CET

CPython 2.7.10
IPython 4.0.2

pandas 0.18.1
geopandas 0+unknown
numpy 1.11.1
shapely 1.5.13
fiona 1.7.0.post2
pyproj 1.9.5.1
rtree 0.8.2

compiler   : GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)
system     : Darwin
release    : 16.4.0
machine    : x86_64
processor  : i386
CPU cores  : 4
interpreter: 64bit
host name  : MacBook-Pro-de-Qucit.local
watermark 1.3.4
```

Thanks in advance!

**Comment by ResidentMario** [comment]
Two things:
* `geoplot` is tough to install via `pip`, I recommend doing so using `conda`. According to `watermark`, your install is missing two of the required libraries: `matplotlib` and `cartopy`. These are sometimes difficult to install with `pip` alone, particularly the latter one.
* You're seeing those errors because you're running in 2.7 and `geoplot` is 3.5+ only right now. Sorry about that...I haven't gotten around to backporting it yet.

**Comment by yassineAlouini** [comment]
@ResidentMario Thanks for the quick feedback. 

For the first point, I have `matplotlib` and `cartopy` installed but I forgot to include them. Sorry for that. 

For the second point, I will use Python 3.5.

**Comment by nkconnor** [comment]
should specify that only 3.5+ is supported in the docs and pypi

**Comment by ResidentMario** [comment]
The upcoming `geoplot@0.3.0` release, which is now Python 3.6 dependent (it uses f-strings, a new 3.6 feature), documents the requirement both in the "Installation" section of the docs and with a badge on the `README.md` landing page in the GitHub repo.
