### ISSUE TITLE
PointPlot does not support `none` facecolor (no fill)

### ISSUE THREAD

**Issue by Casyfill** [ResidentMario/geoplot#31]
I'd like to plot empty circles, but there seems to be no direct way to do that:
While matplotlib offers `facecolor='none'` to remove fill, geoplot sets fill to default in this case.

http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.scatter

**Comment by Casyfill** [comment]
actually, sorry - worked when I replaced `facecolor` with `color`

**Comment by ResidentMario** [comment]
Yep, I do this all the time also. That's `matplotlib` for ya.
