### ISSUE TITLE
Support Multiple legend, Line Legend

### ISSUE THREAD

**Issue by Casyfill** [ResidentMario/geoplot#32]
I am using geoplot to plot a network over the map of NYC.
It works good, but I have troubles with drawing the legend:

```
my_dpi = 96
fig =  plt.figure( figsize=(600/my_dpi, 1500/my_dpi), dpi=my_dpi)
ax1 = plt.subplot(211, projection=gcrs.AlbersEqualArea(central_latitude=40.7128, central_longitude=-74.03))
ax1.margins(0)



gplt.polyplot(hoods['geometry'], ax=ax1, **polyplot_kwargs);
gplt.pointplot(sl, ax=ax1, limits=(1, 15), scale='count', **pointplot_kwargs,
               legend=True, legend_var='scale',
               legend_values=[10000, 50000, 100000],
               legend_labels=['10,000','50,000', '100,000'],
               legend_kwargs=legend_kwargs)

gplt.sankey(lines.query('count > 5000'), limits=(1, 15), 
            start='start_point', end='end_point',
            scale='count', ax=ax1, **lines_kwargs)

ax1.set_ylim((-6000, 12000));
ax1.set_xlim((-6000, 11500));
ax1.text(0, 0.88, 'Citibike Network', color='#004C74', 
         alpha=1, fontsize=16, transform = ax1.transAxes)
ax1.text(0, 0.84, 'May-Sep 2016', color='#004C74', 
         alpha=1, fontsize=10, transform = ax1.transAxes)

```

And the result is 
![download_network1](https://cloud.githubusercontent.com/assets/2675621/25828252/3d136452-341d-11e7-8943-74a163c5f878.png)

However, what I want is 
1) legend of lines  (as lines, if possible)
2) legend of circles/points in the same style 

Is there any way to resolve that?

**Comment by Casyfill** [comment]
Right... I guess I'll have to generate it manually.
With that - can we somehow fix the plot style for the legend? 
I definitely would prefer circles to be of the same style as nodes on the map

**Comment by ResidentMario** [comment]
That's a good point. I'll look into it, yeah.

**Comment by Casyfill** [comment]
Actually, hold on. I made a fork and will try to address this style issue.
And who knows, maybe will add line legend as well. 

Will PR after testing
https://github.com/Casyfill/geoplot

**Comment by ResidentMario** [comment]
Closing in favor of #35.
