### ISSUE TITLE
fix Sankey Caps - or provide option?

### ISSUE THREAD

**Issue by Casyfill** [ResidentMario/geoplot#33]
I am working with Sankey - I use it to generate a network of O-D trips for NYC citibikes.
It is awesome, but one thing I found is that each edge caps with the square (?) - meaning that if radius of the node circle is similar to the width of the edge, we see edge corners.

It would be awesome to be able to either make round caps or stop edges at the node itself (see image below)

![screenshot 2017-05-11 16 11 36](https://cloud.githubusercontent.com/assets/2675621/25969978/041a6b7e-3665-11e7-82ba-c1dc9bfa7e48.png)

**Comment by ResidentMario** [comment]
Since you closed this, what's your resolution? This might be a better default parameter.

**Comment by Casyfill** [comment]
'solid_capstyle':'round' for sankey line kwargs
