### ISSUE TITLE
Choropleth map behavior

### ISSUE THREAD

**Issue by jsh9** [ResidentMario/geoplot#42]
Hi, I was looking at the choropleth map function of this module, but the input argument seems a little bit confusing:

1) The first input argument, df, is the "data being plotted". From your example, I deduced that df should be the information obtained from some shapefiles. If this is true, could you update the documentation and variable name, so that it is less confusing?

2) From the documentation (as well as the examples), I cannot figure out how to plot continuously-valued data (for example, population density per state). The more intuitive input structure, in my opinion, is using a Python dictionary, with keys being names of polygons (corresponding to the polygons in the shapefiles), and values being the values to be mapped into colors (which can either be categorical or continuous). In this way, potential users who have their own shapefiles and the corresponding data (stored as a Python dict) can easily plot a choropleth map.

3) The USA map lacks Alaska and Hawaii.

Incidentally, I was working on a similar choropleth map plotting problem, for which I submitted a pull request to matplotlib: https://github.com/matplotlib/basemap/pull/366.  I added Alaska and Hawaii elegantly into the corner of the USA map, and I also used Python dictionary as my input data structure.

Just offering my two cents.

**Comment by ResidentMario** [comment]
I'm revising the documentation right now, so I'll keep (1) in mind.

To plot continuously valued data, you need to specify `k=None`, which will turn off the categorical binning. So for example, from the documentation:

```
gplt.choropleth(census_tracts, hue=percent_white, projection=gcrs.AlbersEqualArea(),
                cmap='Purples', linewidth=0.5, k=None, legend=True)
```

I get that this might be confusing, so again I'll keep (2) in mind.

With (3), the USA map lacks Alaska and Hawaii on purpose. Insetting is an interesting idea, but outside of the scope of this module for now, there are many other things that need to be worked on before that.

**Comment by ResidentMario** [comment]
I've significantly revised the documentation again. I doubt the documentation and the API surface totally satisfies all readers, but I think it's good enough, a strikes the right balance between novel and familiar (a lot of this was grafted from the way `seaborn` organizes its API). Closing this out for now. More API feedback is always welcome, though.

**Comment by egovtechindia** [comment]
Hey, I would like to label field on map through geoplot.choropleth function. Please update.
