### ISSUE TITLE
GeoPlot on Windows

### ISSUE THREAD

**Issue by geodesy99** [ResidentMario/geoplot#45]
https://residentmario.github.io/geoplot/installing.html says "Windows ... Unforunately geoplot is not available on Windows yet due to an unresolved dependency issue. Sorry."

Seemed to install okay on Windows 10 using conda and usable in Jupyter notebooks. See attachment.
But not on the first try, in the 'stock' environment. See attachment. 

![geoplot_2017-10-23 22_21_56-](https://user-images.githubusercontent.com/742406/31927867-b00a478a-b84a-11e7-8141-ed5a4707dc83.png)

I did have to set up an environment and install GeoPandas first, then Geoplot. Your tutorial documentation should provide a link to Quilt - since it appears as code, it isn't obvious if it was part of GeoPlot or not to a beginner.

(C:\Users\Colossus\Anaconda3\envs\GeoProjects) C:\Users\Colossus>conda install -c conda-forge geopandas
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Users\Colossus\Anaconda3\envs\GeoProjects:

The following NEW packages will be INSTALLED:

    backports:                     1.0-py36_1            conda-forge
    backports.functools_lru_cache: 1.4-py36_1            conda-forge
    click:                         6.7-py36_0            conda-forge
    click-plugins:                 1.0.3-py36_0          conda-forge
    cligj:                         0.4.0-py36_0          conda-forge
    curl:                          7.49.1-vc14_2         conda-forge [vc14]
    cycler:                        0.10.0-py36_0         conda-forge
    descartes:                     1.1.0-py36_0          conda-forge
    expat:                         2.2.1-vc14_0          conda-forge [vc14]
    fiona:                         1.7.9-py36_1          conda-forge
    freetype:                      2.7-vc14_1            conda-forge [vc14]
    freexl:                        1.0.2-vc14_2          conda-forge [vc14]
    gdal:                          2.1.3-py36_vc14_4     conda-forge [vc14]
    geopandas:                     0.3.0-py36_0          conda-forge
    geos:                          3.5.1-vc14_1          conda-forge [vc14]
    hdf4:                          4.2.12-vc14_0         conda-forge [vc14]
    hdf5:                          1.8.18-vc14_1         conda-forge [vc14]
    icc_rt:                        2017.0.4-h97af966_0
    icu:                           58.1-vc14_1           conda-forge [vc14]
    intel-openmp:                  2018.0.0-hcd89f80_7
    jpeg:                          9b-vc14_1             conda-forge [vc14]
    kealib:                        1.4.7-vc14_3          conda-forge [vc14]
    krb5:                          1.14.2-vc14_0         conda-forge [vc14]
    libiconv:                      1.14-vc14_4           conda-forge [vc14]
    libnetcdf:                     4.4.1.1-vc14_6        conda-forge [vc14]
    libpng:                        1.6.28-vc14_1         conda-forge [vc14]
    libpq:                         9.6.3-vc14_0          conda-forge [vc14]
    libspatialindex:               1.8.5-vc14_1          conda-forge [vc14]
    libspatialite:                 4.3.0a-vc14_15        conda-forge [vc14]
    libtiff:                       4.0.7-vc14_0          conda-forge [vc14]
    libxml2:                       2.9.5-vc14_0          conda-forge [vc14]
    matplotlib:                    2.1.0-py36_0          conda-forge
    mkl:                           2018.0.0-h36b65af_4
    munch:                         2.2.0-py36_0          conda-forge
    numpy:                         1.13.3-py36ha320f96_0
    openjpeg:                      2.3.0-vc14_0          conda-forge [vc14]
    pandas:                        0.20.3-py36_1         conda-forge
    pcre:                          8.39-vc14_0           conda-forge [vc14]
    proj4:                         4.9.3-vc14_4          conda-forge [vc14]
    psycopg2:                      2.7.3.1-py36_0        conda-forge
    pyproj:                        1.9.5.1-py36_0        conda-forge
    pyqt:                          5.6.0-py36_4          conda-forge
    pysal:                         1.14.2-py36_1         conda-forge
    pytz:                          2017.2-py36_0         conda-forge
    qt:                            5.6.2-vc14_2          conda-forge [vc14]
    rtree:                         0.8.3-py36_0          conda-forge
    scipy:                         0.19.1-py36h7565378_3
    shapely:                       1.6.1-py36_1          conda-forge
    sip:                           4.18-py36_1           conda-forge
    sqlalchemy:                    1.1.13-py36_0         conda-forge
    sqlite:                        3.13.0-vc14_0         conda-forge [vc14]
    xerces-c:                      3.1.4-vc14_2          conda-forge [vc14]
    zlib:                          1.2.8-vc14_3          conda-forge [vc14]

Proceed ([y]/n)? y

jpeg-9b-vc14_1 100% |###############################| Time: 0:00:00 419.24 kB/s
zlib-1.2.8-vc1 100% |###############################| Time: 0:00:00 559.25 kB/s
curl-7.49.1-vc 100% |###############################| Time: 0:00:00 526.12 kB/s
hdf5-1.8.18-vc 100% |###############################| Time: 0:00:19 687.67 kB/s
icu-58.1-vc14_ 100% |###############################| Time: 0:00:29 765.79 kB/s
libiconv-1.14- 100% |###############################| Time: 0:00:01 562.68 kB/s
libpng-1.6.28- 100% |###############################| Time: 0:00:00 559.08 kB/s
libtiff-4.0.7- 100% |###############################| Time: 0:00:01 476.98 kB/s
backports-1.0- 100% |###############################| Time: 0:00:00   0.00  B/s
click-6.7-py36 100% |###############################| Time: 0:00:00 261.89 kB/s
freetype-2.7-v 100% |###############################| Time: 0:00:01 436.01 kB/s
libnetcdf-4.4. 100% |###############################| Time: 0:00:00 556.16 kB/s
libxml2-2.9.5- 100% |###############################| Time: 0:00:04 698.61 kB/s
numpy-1.13.3-p 100% |###############################| Time: 0:00:02   1.79 MB/s
openjpeg-2.3.0 100% |###############################| Time: 0:00:01 495.75 kB/s
pytz-2017.2-py 100% |###############################| Time: 0:00:00 214.11 kB/s
sip-4.18-py36_ 100% |###############################| Time: 0:00:00 371.30 kB/s
sqlalchemy-1.1 100% |###############################| Time: 0:00:02 740.63 kB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00 989.30 kB/s
pyqt-5.6.0-py3 100% |###############################| Time: 0:00:07 670.47 kB/s
backports.func 100% |###############################| Time: 0:00:00   0.00  B/s
gdal-2.1.3-py3 100% |###############################| Time: 0:01:01 865.54 kB/s
pandas-0.20.3- 100% |###############################| Time: 0:00:11 753.15 kB/s
matplotlib-2.1 100% |###############################| Time: 0:00:10 641.83 kB/s

(C:\Users\Colossus\Anaconda3\envs\GeoProjects) C:\Users\Colossus>conda install geoplot -c conda-forge
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Users\Colossus\Anaconda3\envs\GeoProjects:

The following NEW packages will be INSTALLED:

    cartopy:     0.15.1-py36_4 conda-forge
    geoplot:     0.1.1-py_0    conda-forge
    libxslt:     1.1.29-vc14_5 conda-forge [vc14]
    lxml:        4.1.0-py36_0  conda-forge
    olefile:     0.44-py36_0   conda-forge
    owslib:      0.15.0-py_0   conda-forge
    patsy:       0.4.1-py36_0  conda-forge
    pillow:      4.3.0-py36_0  conda-forge
    pyepsg:      0.3.2-py36_0  conda-forge
    pyshp:       1.2.12-py_0   conda-forge
    seaborn:     0.8.1-py36_0  conda-forge
    statsmodels: 0.8.0-py36_0  conda-forge

Proceed ([y]/n)? y

olefile-0.44-p 100% |###############################| Time: 0:00:00 262.21 kB/s
libxslt-1.1.29 100% |###############################| Time: 0:00:00 527.79 kB/s
pillow-4.3.0-p 100% |###############################| Time: 0:00:00   1.21 MB/s
lxml-4.1.0-py3 100% |###############################| Time: 0:00:01 933.02 kB/s
patsy-0.4.1-py 100% |###############################| Time: 0:00:00 411.64 kB/s
statsmodels-0. 100% |###############################| Time: 0:00:09 700.37 kB/s
seaborn-0.8.1- 100% |###############################| Time: 0:00:01 273.89 kB/s

(C:\Users\Colossus\Anaconda3\envs\GeoProjects) C:\Users\Colossus>pip install quilt
Collecting quilt
  Downloading quilt-2.7.0.tar.gz
Collecting appdirs>=1.4.0 (from quilt)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting future>=0.16.0 (from quilt)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.5MB/s
Requirement already satisfied: packaging>=16.8 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from quilt)
Requirement already satisfied: pandas>=0.19.2 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from quilt)
Collecting pyarrow>=0.4.0 (from quilt)
  Downloading pyarrow-0.7.1-cp36-cp36m-win_amd64.whl (2.6MB)
    100% |████████████████████████████████| 2.6MB 1.9MB/s
Requirement already satisfied: pyOpenSSL>=16.2.0 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from quilt)
Collecting pyyaml>=3.12 (from quilt)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 1.8MB/s
Requirement already satisfied: requests>=2.12.4 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from quilt)
Collecting responses<0.6.1,>=0.5.1 (from quilt)
  Downloading responses-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from quilt)
Collecting tables>=3.3.0 (from quilt)
  Downloading tables-3.4.2-1-cp36-cp36m-win_amd64.whl (2.5MB)
    100% |████████████████████████████████| 2.5MB 1.7MB/s
Collecting tqdm>=4.11.2 (from quilt)
  Downloading tqdm-4.19.4-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 1.2MB/s
Collecting xlrd>=1.0.0 (from quilt)
  Downloading xlrd-1.1.0-py2.py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 2.1MB/s
Requirement already satisfied: pyparsing in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from packaging>=16.8->quilt)
Requirement already satisfied: python-dateutil>=2 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from pandas>=0.19.2->quilt)
Requirement already satisfied: pytz>=2011k in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from pandas>=0.19.2->quilt)
Requirement already satisfied: numpy>=1.7.0 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from pandas>=0.19.2->quilt)
Requirement already satisfied: cryptography>=1.9 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from pyOpenSSL>=16.2.0->quilt)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from requests>=2.12.4->quilt)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from requests>=2.12.4->quilt)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from requests>=2.12.4->quilt)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from requests>=2.12.4->quilt)
Collecting cookies (from responses<0.6.1,>=0.5.1->quilt)
  Downloading cookies-2.2.1-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 2.3MB/s
Collecting numexpr>=2.5.2 (from tables>=3.3.0->quilt)
  Downloading numexpr-2.6.4-cp36-none-win_amd64.whl (86kB)
    100% |████████████████████████████████| 92kB 2.4MB/s
Requirement already satisfied: asn1crypto>=0.21.0 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from cryptography>=1.9->pyOpenSSL>=16.2.0->quilt)
Requirement already satisfied: cffi>=1.7 in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from cryptography>=1.9->pyOpenSSL>=16.2.0->quilt)
Requirement already satisfied: pycparser in c:\users\colossus\anaconda3\envs\geoprojects\lib\site-packages (from cffi>=1.7->cryptography>=1.9->pyOpenSSL>=16.2.0->quilt)
Building wheels for collected packages: quilt, future, pyyaml
  Running setup.py bdist_wheel for quilt ... done
  Stored in directory: C:\Users\Colossus\AppData\Local\pip\Cache\wheels\41\dd\ee\c487611a88a67180d0b88de92417ec9556957d6e8776a68ef0
  Running setup.py bdist_wheel for future ... done
  Stored in directory: C:\Users\Colossus\AppData\Local\pip\Cache\wheels\c2\50\7c\0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: C:\Users\Colossus\AppData\Local\pip\Cache\wheels\2c\f7\79\13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
Successfully built quilt future pyyaml
Installing collected packages: appdirs, future, pyarrow, pyyaml, cookies, responses, numexpr, tables, tqdm, xlrd, quilt
Successfully installed appdirs-1.4.3 cookies-2.2.1 future-0.16.0 numexpr-2.6.4 pyarrow-0.7.1 pyyaml-3.12 quilt-2.7.0 responses-0.6.0 tables-3.4.2 tqdm-4.19.4 xlrd-1.1.0

(C:\Users\Colossus\Anaconda3\envs\GeoProjects) C:\Users\Colossus>quilt install ResidentMario/geoplot_data
Downloading 2ed72f0dcadd6ae5754664b6dc81ac0f52555d68f285f5f15267bea05d8496a5 (1/17)...
100%|█████████████████████████████████████████████████████████████████████████████| 1.67K/1.67K [00:00<00:00, 1.60MB/s]
Downloading 34bd0416df19c624f79475cf22bd9380f9c442a013ac5f2376157ad482e18aed (2/17)...
100%|█████████████████████████████████████████████████████████████████████████████| 1.33K/1.33K [00:00<00:00, 1.33MB/s]
Downloading 541fc9abd92d5c1e9f842a1a7fcdf667eb15dfd0358f47b84626909134b294c0 (3/17)...
100%|█████████████████████████████████████████████████████████████████████████████████████████| 141/141 [00:00<?, ?B/s]
Downloading 6ed12561ef35e5a1c9494fd23d565020649abccded02ce01ee105599826552ae (4/17)...
100%|██████████████████████████████████████████████████████████████████████████████████| 975/975 [00:00<00:00, 927KB/s]
Downloading 777fcc2d4ccda556acb1786990b14ae99e420d46f40b3c4edbd99a3fa63760b8 (5/17)...
100%|██████████████████████████████████████████████████████████████████████████████| 16.5K/16.5K [00:00<00:00, 117KB/s]
Downloading a01523501f4f24d413299ffb92a797b2cc84d503a4d90dfefa67901aa6c2c445 (6/17)...
100%|██████████████████████████████████████████████████████████████████████████████| 1.42M/1.42M [00:01<00:00, 900KB/s]
Downloading a015564a938943ce2aea8f317e1e53058233ce58a5bd4cdd125e59f782ef064e (7/17)...
100%|██████████████████████████████████████████████████████████████████████████████| 2.84M/2.84M [00:02<00:00, 998KB/s]
Downloading ba883b9d8a194028cb83f2fc75fedbc88cc072bfa863337a554bf972f4d604d5 (8/17)...
100%|██████████████████████████████████████████████████████████████████████████████| 1.13M/1.13M [00:01<00:00, 707KB/s]
Downloading babd0c3d702e85dacc7ad2f08250bf9823a6a7295367a110f130188e356fa7db (9/17)...
100%|██████████████████████████████████████████████████████████████████████████████| 3.44M/3.44M [00:07<00:00, 446KB/s]
Downloading c19a467e07d134f78b35f0d90354f50a7b696919ecbf53fb205f39780007e372 (10/17)...
100%|████████████████████████████████████████████████████████████████████████████████| 135K/135K [00:00<00:00, 561KB/s]
Downloading c794f51e6c045c775483df5f071881b9dde247ab4a62916897d952de92e87a75 (11/17)...
100%|██████████████████████████████████████████████████████████████████████████████| 94.2K/94.2K [00:00<00:00, 453KB/s]
Downloading cbdfc111c7f8b69c7da6a4c0ee191f780355deaafd90ac3b504262445f9638dc (12/17)...
100%|██████████████████████████████████████████████████████████████████████████████| 1.42M/1.42M [00:04<00:00, 347KB/s]
Downloading d2dcdbb925f5b02c9bf8600fe632db0ba0c1ea3b598e9b0ff24b8826f6e805b3 (13/17)...
100%|████████████████████████████████████████████████████████████████████████████████| 243K/243K [00:00<00:00, 608KB/s]
Downloading e128404cfc2cd0c4c749671ade13e9be39b22e924ddb601370ac3ff02c2bbd81 (14/17)...
100%|████████████████████████████████████████████████████████████████████████████████| 117K/117K [00:00<00:00, 592KB/s]
Downloading e134e406457a79959f52545b0d1fc75a8fb217b737889836685c878fc8d7e6e1 (15/17)...
100%|████████████████████████████████████████████████████████████████████████████████| 395K/395K [00:00<00:00, 577KB/s]
Downloading f1609dd6f76946cc6c1bdb17134ee598fe346bd013a6e7a749534acaf4d73d57 (16/17)...
100%|████████████████████████████████████████████████████████████████████████████████| 686K/686K [00:01<00:00, 505KB/s]
Downloading ff65dd10cb042b95a1cf5489aab3812e1e468eedc51fba7e3933e47b16b2775a (17/17)...
100%|█████████████████████████████████████████████████████████████████████████████| 1.77K/1.77K [00:00<00:00, 1.77MB/s]

(C:\Users\Colossus\Anaconda3\envs\GeoProjects) C:\Users\Colossus>

**Comment by ResidentMario** [comment]
Thanks for reporting!

Indeed, `geoplot` should now work on Windows. This is due to recent changes in the [library feedstock](https://github.com/ResidentMario/geoplot-feedstock) that came as a part of publishing the `0.1.1` version. I just hadn't gotten around to updating all of the documentation to reflect this fact just yet. Now I have!

You don't bring it up explicitly, but the `matplotlib` warning in your screenshot is interesting. I will open an issue to look into that.

And I've added references to the `quilt` package in the tutorial and the examples.
