### ISSUE TITLE
Import error in Windows with 32 bit python 2.7

### ISSUE THREAD

**Issue by bidhya** [ResidentMario/geoplot#47]
I installed geoplot on top of Anaconda Python 2.7 (32 bit) using conda-forge channel mentioned in the documentation. But I cannot import this package.

`import geoplot as gplt`
results in following error

ImportError                               Traceback (most recent call last)
<ipython-input-5-7074a0aa9e7e> in <module>()
----> 1 import geoplot as gplt

ImportError: No module named geoplot

Can you please let me if geoplot works on Windows with 32 bit Python 2.7. Did not find this information anywhere in the documentation.

**Comment by ResidentMario** [comment]
Hi! `geoplot` requires Python version 3.5 or newer (see #24). How were you were able to install on 2.7? The feedstock [explicitly forbids that](https://github.com/conda-forge/geoplot-feedstock/blob/master/recipe/meta.yaml#L14); or, I thought it did.

The error makes it sound like you don't have it installed at all, however. What do you get when you run `conda list`?

OS and 32 bits shouldn't matter.
