### ISSUE TITLE
Bug: Unknown property legend_values in gplt.choropleth

### ISSUE THREAD

**Issue by kartikdesikan** [ResidentMario/geoplot#54]
Hi,
I don't see legend_values in gplt.choropleth source code and of course while trying to run the command I got the error AttributeError: Unknown property legend_values

My question further is that I have a categorical column with values VLOW, LOW, MED, HIGH. I wanted to represent my geomap with:
(a) Legend with this specific order VLOW, LOW, MED, HIGH
(b) Colors of my choice say [darkred, red, blue, green] to make intuitive sense of the labels.

Part (a) as per my understanding would work by using legend_values = ['VLOW', 'LOW', 'MED', 'HIGH'] and legend_labels= ['VLOW', 'LOW', 'MED', 'HIGH'] with categorical = True. Currently as I can only use legend_labels, the legend label order is right, but the values in the map don't match the legend

I have no idea about how to do part (b)

Please help. Thanks!

**Comment by ResidentMario** [comment]
Yep, this is a bug. :face_with_head_bandage: Sorry for not looking at this earlier, I'll put this on the to-do list for `0.2.1`.

**Comment by ResidentMario** [comment]
Fixed prior to #114.
