### ISSUE TITLE
Version tag is out of date

### ISSUE THREAD

**Issue by ResidentMario** [ResidentMario/geoplot#61]
In the `0.2.0` release I neglected to change the `__version__` tag at the top of the file from `0.1.2` to `0.2.0`. Making a note of this here, for anyone that uses that tag when reporting an issue. If/when I release a `0.2.1` I will fix this, but it's too minor an issue to increment the version history for!

**Comment by QuLogic** [comment]
Can you push the git tag for 0.2.0 also?

**Comment by ResidentMario** [comment]
Done. If I may ask, what do you need the tag for? I thought it was only necessary for uploading to PyPi, but `twine` doesn't necessitate that anymore.

**Comment by QuLogic** [comment]
It's useful for more than just that. You can't really go back from tarball to git without the tag without a bit of sleuthing (e.g., the version wasn't right this time, so you can't necessarily rely on that). The PyPI tarball doesn't contain tests, so if I want to run tests when making a package, I need to pull the tagged version from GitHub. Also, if any patches are needed downstream, the tag makes this simple to do.

**Comment by ResidentMario** [comment]
Fixed in the newest bugfix release, `0.2.1`.

**Comment by ResidentMario** [comment]
I've created the tag now, thanks for the spot.
