### ISSUE TITLE
Error for importing in jupyter notebook

### ISSUE THREAD

**Issue by rifatSDAS** [ResidentMario/geoplot#64]
Hi, I got this error message in jupyter notebook while importing geoplot.

"py27\lib\site-packages\geoplot\geoplot.py", line 1475
    def sankey(*args, projection=None,
                               ^
SyntaxError: invalid syntax"

Is there any solution?

**Comment by ResidentMario** [comment]
`geoplot` is Python 3 only, and you're attempting to use with Python 2.7. Python 2.7 [reaches EOL in little more than a year for now](https://pythonclock.org/), so there's never been a good reason for me to work on backwards compatibility for this package. Sorry!
