### ISSUE TITLE
Add dependency to doc

### ISSUE THREAD

**Issue by SylvainLan** [ResidentMario/geoplot#66]
Hi, 

I'm beginning to use your library and just wanted to share the troubles I went through to install the library from `pip`. 
Maybe it should be nice to have a Dependency section in the README of this project. 
I used this information [from cartopy](https://scitools.org.uk/cartopy/docs/v0.15/installing.html#requirements) to download all the requirements, so maybe just this link can be enough.

Thanks for the wonderful work done btw.

**Comment by ResidentMario** [comment]
Actually the README already states that you should run `conda install geoplot -c conda-forge` to install.
