### ISSUE TITLE
Geopandas __pysal_choro() will change to -_mapclassify_choro()

### ISSUE THREAD

**Issue by martinfleis** [ResidentMario/geoplot#67]
Hi,

GeoPandas is switching from PySAL to mapclassify due to new structure of PySAL. Since next release the function `__pysal_choro()` will change to -_`mapclassify_choro()`. It will affect your `_discrete_colorize()` I am afraid. 

Here is that PR which contains this change: https://github.com/geopandas/geopandas/pull/872. It is already merged to master.

Do you want me to make PR using `distutils.version` to take care of it?

**Comment by ResidentMario** [comment]
@martinfleis Thanks for the heads up! If you'd like to submit a PR with this fix I would indeed really appreciate it. :smile:
