### ISSUE TITLE
The geopandas version check is failing

### ISSUE THREAD

**Issue by jorisvandenbossche** [ResidentMario/geoplot#72]
Another difficult to reproduce issue ..

On the readthedocs build of our docs, it is now failing the geoplot example in the following way (see full build log https://readthedocs.org/projects/geopandas/builds/8718626/):

```
generating gallery for gallery... [ 50%] plotting_with_geoplot.py
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/geopandas/checkouts/latest/examples/plotting_with_geoplot.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/checkouts/latest/examples/plotting_with_geoplot.py", line 34, in <module>
    import geoplot
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/geoplot/__init__.py", line 1, in <module>
    from .geoplot import (pointplot, polyplot, choropleth, aggplot, cartogram, kdeplot, sankey, voronoi,
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/site-packages/geoplot/geoplot.py", line 18, in <module>
    if LooseVersion(gpd.__version__) >= LooseVersion('0.4.1'):
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

But when re-creating the same environment locally (it is in https://github.com/geopandas/geopandas/blob/master/doc/environment.yml), I can't reproduce this.

**Comment by ResidentMario** [comment]
I will take a look at this on the weekend. Most likely I'm going to copy `_pysal_choro` (or whatever the name of that function is now) out of `geopandas` and into` geoplot`, because dealing with this oblique dependency by inspecting package versions is creating too many issues like this one.

**Comment by jorisvandenbossche** [comment]
If you don't want to copy the function, you should also be able to do

```
try:
    from geopandas.plotting import _mapclassify_choro
except ImportError:
    from geopandas.plottting import __pysal_choro as _mapclassify_choro
```

that should be fully robust without any need for explicit version checking.

**Comment by ResidentMario** [comment]
This is true, but:

* My understanding is that this style of dependency management is discouraged best practices wise. It's better to be explicit.
* This still feels like a band-aid. `__pysal_choro` is a dunded method that was never intended to be publicly relied upon. The fact that I did was the reason we got into this whole mess in the first place. Relying on `_mapclassify_choro` is still kind of sketchy.

**Comment by jorisvandenbossche** [comment]
If you think it is useful, we can make it public (but, that won't make importing easier in the short term, because then you need to check for 3 different spellings ..)

> My understanding is that this style of dependency management is discouraged best practices wise. It's better to be explicit.

Personally, I think in this case that is perfectly fine (you see a lot use of this kind of try except in python)

**Comment by ResidentMario** [comment]
Done in the `0.2.4` release. Ended up just going along with a generic `try`-`catch` block.
