### ISSUE TITLE
Should explicitly depend on descartes

### ISSUE THREAD

**Issue by QuLogic** [ResidentMario/geoplot#73]
It's imported in the top-level `geoplot.py`, but not listed in `install_requires`. It used to be installed by `geopandas`, but that is no longer the case https://github.com/geopandas/geopandas/pull/648.

**Comment by ResidentMario** [comment]
Hmm, this is correct.

**Comment by ResidentMario** [comment]
Done in the `0.2.4` release.

**Comment by QuLogic** [comment]
Thanks!

PS, don't forget to push the 0.2.4 tag.

**Comment by ResidentMario** [comment]
Whoops&mdash;done.
