### ISSUE TITLE
Marker size

### ISSUE THREAD

**Issue by vool** [ResidentMario/geoplot#74]
Hello,

Is there a way to specify the marker size in a pointplot ?

keith

**Comment by ResidentMario** [comment]
Keyword arguments not captured by `pointplot` are forwarded to [`matplotlib.pyplot.scatter`](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.scatter), which includes a parameter for marker size: `s`. So, do e.g. `gplt.pointplot(..., s=100)`.
