### ISSUE TITLE
import data from quilt for the Jupyter Notebook example

### ISSUE THREAD

**Issue by jnicho02** [ResidentMario/geoplot#75]
Just trying out the Jupyter Notebook code locally and hadn't used quilt before. You could add a couple of lines to the python to import the data package.....

``
import quilt
quilt.install("ResidentMario/geoplot_data", force=True)
``

**Comment by ResidentMario** [comment]
As of `geoplot@0.3.0`, the data source has changed. The documentation, examples, notebooks, etcetera now use of a new `geoplot.datasets.get_path` function to retrieve a path to a dataset readable via `geopandas.read_file`. This mirrors what `geoplot` does, and removes the external dependency on `quilt`, resolving this issue in the process.
