### ISSUE TITLE
Highlight the need for lat/lon GeoPandas in Quick Start tutorial

### ISSUE THREAD

**Issue by sanzoghenzo** [ResidentMario/geoplot#76]
First of all, thanks for your work!

I'm starting using the library, and I spent quite some time to figure out that my GeoPandas data should be in lat/lon coordinates.

I know there's a dedicated jupyter notebook for projection and geospatal data, but I'm expecting this important information to be in the QuickStart tutorial, at least with a link to the related notebook.

Maybe the solution is to embed the notebook in the documentation website (via iframe)? I was a little lost after entering the tutorial, I think this is why it took me longer than usual to find the info I needed.

**Comment by ResidentMario** [comment]
> I'm starting using the library, and I spent quite some time to figure out that my GeoPandas data should be in lat/lon coordinates.
>
> I know there's a dedicated jupyter notebook for projection and geospatal data, but I'm expecting this important information to be in the QuickStart tutorial, at least with a link to the related notebook.

Sure, that's a good idea. I've gone ahead and added a comment on that to `QuickStart.ipynb`.


> Maybe the solution is to embed the notebook in the documentation website (via iframe)? I was a little lost after entering the tutorial, I think this is why it took me longer than usual to find the info I needed.

I'm open to ideas about how the documentation can be improved, but I don't think embedding the notebook in the website is a good idea. It's probably not possible anyway&mdash;I'm 80% sure that `nbviewer` has external `iframe` embedding turned off (and if it doesn't, it frankly should).
