### ISSUE TITLE
Argument for geometry column

### ISSUE THREAD

**Issue by a-martin** [ResidentMario/geoplot#78]
I noticed that by default geoplot functions look for the `geometry` column of a given dataframe (e.g.,  `xs = np.array([p.x for p in df.geometry])`).  It would be nice if that column could be specified.  For example, I have a `GeoDataFrame` with polygons in the `geometry` column, but I'd like to play with a `pointplot` of the same data.  I can extract the centroids from the polygons into a new column easily, but I have to rename that column `geometry` (and drop the polygons for instance) in order for geoplot to look at that column rather than the polygons.

**Comment by ResidentMario** [comment]
I actually disagree. I think the "right" thing to do in this case is to use the `set_geometry` function in `geopandas` (documented [here](http://geopandas.org/data_structures.html)) to temporarily designate another column your geometry:

```python
gplt.pointplot(data.set_geometry('points'))
```

This is almost a no-op for `geopandas`. Whereas adding another yet argument to `geoplot` functions would be burdensome on the user.

If you want to avoid munging the data altogether, you can actually pass geometry and/or data directly to `geoplot`. For example, the following is totally valid:

```python
gplt.pointplot(data.points, hue=data.persons_involved, scale=some_other_data.damages_amount)
```
